# permissions for end users to edit cloudbasemains.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cloudbasemain-editor-role
rules:
- apiGroups:
  - cache.example.com
  resources:
  - cloudbasemains
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.example.com
  resources:
  - cloudbasemains/status
  verbs:
  - get
