# permissions for end users to view cloudbasemains.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cloudbasemain-viewer-role
rules:
- apiGroups:
  - cache.example.com
  resources:
  - cloudbasemains
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cache.example.com
  resources:
  - cloudbasemains/status
  verbs:
  - get
